# Generated by Django 4.1.2 on 2022-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
