# Generated by Django 4.1.2 on 2022-11-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_tagmodel_title_userprofilemodel_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagmodel',
            old_name='title',
            new_name='name',
        ),
    ]
